name: disruptive_quantization
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - fonttools=4.55.8
  - freetype=2.12.1
  - icu=75.1
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - liblzma=5.6.4
  - libopenblas=0.3.28
  - libpng=1.6.46
  - libsqlite=3.48.0
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - llvmlite=0.44.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - munkres=1.1.4
  - ncurses=6.5
  - numba=0.61.0
  - numpy=2.1.3
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - pillow=11.1.0
  - pip=25.0
  - pthread-stubs=0.4
  - pyparsing=3.2.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - qhull=2020.2
  - readline=8.2
  - scipy=1.15.1
  - setuptools=75.8.0
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.6
